// <auto-generated />
namespace PadSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AlertOpenIDlength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlertOpenIDlength));
        
        string IMigrationMetadata.Id
        {
            get { return "201310120802107_AlertOpenIDlength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
