// <auto-generated />
namespace PadSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMediaScheme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMediaScheme));
        
        string IMigrationMetadata.Id
        {
            get { return "201309220303319_AddMediaScheme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
