// <auto-generated />
namespace PadSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OutDoorField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OutDoorField));
        
        string IMigrationMetadata.Id
        {
            get { return "201309130222406_OutDoorField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
