//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PadSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class Department
    {
        public Department()
        {
            this.Permissions = new HashSet<Permissions>();
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        [MaxLength(50)]
        [Display(Name = "部门名称")]
        public string Name { get; set; }

        [MaxLength(150)]
        [Display(Name = "部门描述")]
        public string Description { get; set; }

        [MaxLength(50)]
        [Display(Name = "部门领导")]
        public string Leader { get; set; }

        public virtual ICollection<Permissions> Permissions { get; set; }
    }
}
